[project]
name = "pykit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rohit Narayanan", email = "rohit.nn@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
pykit = "pykit:main"

[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"
