[project]
name = "pykit"
version = "0.1.0"
description = "Development kit for python programming"
readme = "README.md"
authors = [{ name = "Rohit Narayanan", email = "rohit.nn@gmail.com" }]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
pykit = "pykit:main"

[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"

[tool.pyright]
typeCheckingMode = "strict"
include = ["packages"]
ignore = ["tests", "**/tests"]
reportMissingTypeStubs = false
reportUnnecessaryTypeIgnoreComment = "error"
venvPath = "."
venv = ".venv"

[tool.ruff.lint.per-file-ignores]
"**/tests/*" = ["ALL"]

[tool.uv.sources]
rn-forge-commons = { workspace = true }
rn-forge-django = { workspace = true }
rn-forge-tooling = { workspace = true }

[tool.uv.workspace]
members = [
  "packages/rn-forge-commons",
  "packages/rn-forge-django",
  "packages/rn-forge-tooling",
]

[dependency-groups]
workspace = ["rn-forge-commons[all]", "rn-forge-django[all]", "rn-forge-tooling"]

docs = [
  "mkdocs>=1.6.1",
  "mkdocs-material>=9.7.6",
  "mkdocs-monorepo-plugin>=1.1.2",
  "mkdocstrings[python]>=1.0.6",
]

dev = [
  { include-group = "workspace" },
  { include-group = "docs" },
  "assertpy>=1.1",
  "django-stubs>=6.0.7",
  "import-linter>=2.3",
  "pandas-stubs>=3.0.5",
  "pyright>=1.1.411",
  "pytest>=9.1.1",
  "pytest-cov>=7.1.0",
  "pytest-django>=4.12.0",
  "pytest-randomly>=4.1.0",
  "rn-forge-commons[excel]",
  "ruff>=0.15.21",
]
