sonar.projectKey=rn-forge_pykit
sonar.organization=rn-forge

sonar.sources=packages/rn-forge-commons/src,packages/rn-forge-django/src
sonar.tests=packages/rn-forge-commons/tests,packages/rn-forge-django/tests

sonar.python.version=3.14
