sonar.projectKey=rn-forge_pykit
sonar.organization=rn-forge

sonar.sources=packages/rn-forge-commons/src,packages/rn-forge-cli/src,packages/rn-forge-tooling/src,packages/rn-forge-web/src,packages/rn-forge-django/src
sonar.tests=packages/rn-forge-commons/tests,packages/rn-forge-cli/tests,packages/rn-forge-tooling/tests,packages/rn-forge-web/tests,packages/rn-forge-django/tests

sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
